# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appdesigne.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sampleLabel = QtWidgets.QLabel(self.centralwidget)
        self.sampleLabel.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.sampleLabel.setObjectName("sampleLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 151, 16))
        self.label_4.setObjectName("label_4")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(10, 500, 75, 23))
        self.startButton.setObjectName("startButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 10, 751, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        #self.signalWidget = signalWidget(self.horizontalLayoutWidget)
        #self.signalWidget.setObjectName("signalWidget")
       # self.horizontalLayout.addWidget(self.signalWidget)
       # self.filtrSignalWidget = filtrSignalWidget(self.horizontalLayoutWidget)
        #self.filtrSignalWidget.setObjectName("filtrSignalWidget")
        #self.horizontalLayout.addWidget(self.filtrSignalWidget)
        self.SliderCrit = QtWidgets.QSlider(self.centralwidget)
        self.SliderCrit.setGeometry(QtCore.QRect(10, 140, 160, 22))
        self.SliderCrit.setOrientation(QtCore.Qt.Horizontal)
        self.SliderCrit.setObjectName("SliderCrit")
        self.SliderFreq = QtWidgets.QSlider(self.centralwidget)
        self.SliderFreq.setGeometry(QtCore.QRect(10, 240, 160, 22))
        self.SliderFreq.setOrientation(QtCore.Qt.Horizontal)
        self.SliderFreq.setObjectName("SliderFreq")
        self.SliderOrder = QtWidgets.QSlider(self.centralwidget)
        self.SliderOrder.setGeometry(QtCore.QRect(10, 330, 160, 22))
        self.SliderOrder.setOrientation(QtCore.Qt.Horizontal)
        self.SliderOrder.setObjectName("SliderOrder")
        self.spinBoxCrit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxCrit.setGeometry(QtCore.QRect(10, 110, 161, 22))
        self.spinBoxCrit.setObjectName("spinBoxCrit")
        self.SpinBoxFreq = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SpinBoxFreq.setGeometry(QtCore.QRect(10, 210, 161, 22))
        self.SpinBoxFreq.setObjectName("SpinBoxFreq")
        self.spinBoxOrger = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxOrger.setGeometry(QtCore.QRect(10, 300, 161, 22))
        self.spinBoxOrger.setObjectName("spinBoxOrger")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 21))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_WAV_file = QtWidgets.QAction(MainWindow)
        self.actionSave_WAV_file.setObjectName("actionSave_WAV_file")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCtrl_O = QtWidgets.QAction(MainWindow)
        self.actionCtrl_O.setObjectName("actionCtrl_O")
        self.actionOpen_WAV_file_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_WAV_file_2.setObjectName("actionOpen_WAV_file_2")
        self.actionSetting_filter = QtWidgets.QAction(MainWindow)
        self.actionSetting_filter.setObjectName("actionSetting_filter")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_WAV_file_2)
        self.menuFile.addAction(self.actionSave_WAV_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSetting_filter)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sampleLabel.setText(_translate("MainWindow", "Treks"))
        self.label_2.setText(_translate("MainWindow", "Критическая частота"))
        self.label_3.setText(_translate("MainWindow", "Частота дискретизации"))
        self.label_4.setText(_translate("MainWindow", "Порядок фильтра"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_WAV_file.setText(_translate("MainWindow", "Save WAV-file"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCtrl_O.setText(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_WAV_file_2.setText(_translate("MainWindow", "Open  WAV-file"))
        self.actionSetting_filter.setText(_translate("MainWindow", "Setting filter"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from filtrsignalwidget import filtrSignalWidget
from signalwidget import signalWidget
